# Generated by Django 5.2.6 on 2025-09-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
