# Generated by Django 5.2.6 on 2025-12-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.BooleanField(default=False),
        ),
    ]
