# Generated by Django 5.2.6 on 2025-12-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_userprofile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sound_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
