# Generated by Django 5.2.6 on 2025-12-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_userprofile_sound_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sound_enabled',
        ),
    ]
